[package]
name = "rumary-api"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
reqwest.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true
pretty_env_logger.workspace = true
dns-lookup = "3.0.1"
log.workspace = true
http = "1.4.0"
jsonwebtoken = { version = "11.0", features = ["aws_lc_rs", "use_pem"] }

axum-extra = { version = "0.12", features = ["typed-header", "cookie"] }
dotenv = "0.15"
rumary-dto = { path = "../rumary-dto", features = ["dto_api", "domain_api", "domain_perms"] }
rumary-perms = { path = "../rumary-perms" }

chacha20poly1305 = "0.11.0-rc.3"
rand = "0.10"
totp-rs = { version = "6.0.0", features = ["otpauth", "gen_secret"] }
hex = "0.4.3"
moka = "0.12.15"

