[package]
name = "rumary-api"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
reqwest.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
dns-lookup = "3.0.1"

rumary-dto = { path = "../rumary-dto", features = ["dto_api"] }
