use crate::config::DatabaseConfig;
use crate::error::{AppError, AppResult};
use crate::repo::repository::{
    ConfigurationRepository, InstanceRepository, RightsRepository, RolesRepository,
    SessionRepository, SettingsRepository, TotpRepository, UserRepository,
};
use crate::service::right::Rights;
use async_trait::async_trait;
use chrono::{DateTime, Utc};
use rumary_dto::domain::api::{Configuration, Instance, NewConfiguration, NewInstance, NewRole, NewTotpUser, NewUser, RefreshSessionUpdate, /*RightDefinition,*/ RightFromRow, /*RightId,*/ RightKey, TotpUser, UpdateConfiguration, UpdateInstance, UpdateRoleDb, User, UserSession};
use rumary_dto::domain::auth::tokens::TokenId;
use rumary_dto::domain::configuration::ConfigurationId;
use rumary_dto::domain::instance::InstanceId;
use rumary_dto::domain::user::{Login, UserId};
use rumary_dto::dto::api::db::role::RoleFromRow;
use serde::Serialize;
use sqlx::postgres::{PgConnectOptions, PgPoolOptions};
use sqlx::{PgPool, Pool, Postgres, Row};
use std::path::{Path, PathBuf};
use std::time::Duration;

#[derive(Clone)]
pub struct PostgresRepo {
    pool: PgPool,
    rights_updates: tokio::sync::mpsc::Sender<Rights>,
}

#[allow(unused)]
impl PostgresRepo {
    pub async fn connect(
        config: DatabaseConfig,
        rights_updates: tokio::sync::mpsc::Sender<Rights>,
    ) -> AppResult<Self> {
        let options = PgConnectOptions::new()
            .host(&config.host)
            .port(config.port)
            .username(&config.user)
            .password(&config.password)
            .database(&config.db_name);

        let pool = PgPoolOptions::new()
            .max_connections(20)
            .acquire_timeout(Duration::from_secs(8))
            .connect_with(options)
            .await?;

        Ok(Self {
            pool,
            rights_updates,
        })
    }

    pub fn get_pool(&self) -> Pool<Postgres> {
        self.pool.clone()
    }

    async fn ensure_rights_table(&self) -> AppResult<()> {
        sqlx::query(
            r#"
            create table if not exists rights
            (
                id            bigint generated by default as identity primary key,
                key           text not null unique,
                default_value boolean not null,
                active        boolean not null default true
            )
            "#,
        )
        .execute(&self.pool)
        .await?;

        Ok(())
    }

    async fn load_rights(&self) -> AppResult<RightFromRow> {
        // self.ensure_rights_table().await?;
        todo!()
        // let rows = sqlx::query(
        //     r#"
        //     select id, key, default_value, active
        //     from rights
        //     order by id
        //     "#,
        // )
        // .fetch_all(&self.pool)
        // .await?;
        //
        // let mut rights = RightFromRow(Default::default());
        //
        // for row in rows {
        //     let id: i64 = row.try_get("id")?;
        //     if id < 0 {
        //         return Err(AppError::Internal(format!("negative right id {id}")));
        //     }
        //
        //     let key: String = row.try_get("key")?;
        //     let default: bool = row.try_get("default_value")?;
        //     let active: bool = row.try_get("active")?;
        //
        //     rights.0.insert(
        //         key,
        //         RightDefinition {
        //             id: RightId::new(id as usize),
        //             default,
        //             active,
        //         },
        //     );
        // }
        //
        // Ok(rights)
    }

    async fn publish_rights(&self) -> AppResult<()> {
        let rights = self.load_rights().await?;
        self.rights_updates.send(rights.into()).await?;
        Ok(())
    }
}
#[allow(unused)]
#[async_trait]
impl UserRepository for PostgresRepo {
    type Error = AppError;

    async fn create_user(&self, user: NewUser) -> AppResult<User> {
        todo!()
    }

    async fn find_user(&self, user_id: UserId) -> AppResult<Option<User>> {
        todo!()
    }

    async fn find_user_by_login(&self, login: Login) -> AppResult<Option<User>> {
        todo!()
    }

    async fn delete_user(&self, user_id: UserId) -> AppResult<()> {
        todo!()
    }

    async fn list_users(&self) -> AppResult<Vec<User>> {
        todo!()
    }
}
#[allow(unused)]
#[async_trait]
impl TotpRepository for PostgresRepo {
    type Error = AppError;

    async fn create_totp_user(&self, user: NewTotpUser) -> AppResult<TotpUser> {
        todo!()
    }

    async fn totp_user_confirmed(&self, user_id: UserId) -> AppResult<TotpUser> {
        todo!()
    }

    async fn find_totp_user(&self, user_id: UserId) -> AppResult<Option<TotpUser>> {
        todo!()
    }

    async fn delete_totp_user(&self, user_id: UserId) -> AppResult<()> {
        todo!()
    }
}
#[allow(unused)]
#[async_trait]
impl SessionRepository for PostgresRepo {
    type Error = AppError;

    async fn find_user_by_token_id(&self, token_id: TokenId) -> AppResult<Option<UserSession>> {
        todo!()
    }

    async fn save_refresh_session(
        &self,
        user_id: UserId,
        session: RefreshSessionUpdate,
    ) -> AppResult<()> {
        todo!()
    }

    async fn clear_refresh_session(&self, user_id: UserId) -> AppResult<()> {
        todo!()
    }
}

#[allow(unused)]
#[async_trait]
impl SettingsRepository for PostgresRepo {
    type Error = AppError;

    async fn save_instance_dir_path(&self, path: &Path) -> Result<(), Self::Error> {
        todo!()
    }

    async fn get_instances_dir_path(&self) -> Result<PathBuf, Self::Error> {
        todo!()
    }

    async fn delete_instances_dir_path(&self) -> Result<PathBuf, Self::Error> {
        todo!()
    }
}
#[allow(unused)]
#[async_trait]
impl InstanceRepository for PostgresRepo {
    type Error = AppError;

    async fn create_instance(&self, new_instance: NewInstance) -> Result<Instance, Self::Error> {
        todo!()
    }

    async fn update_instance(
        &self,
        update_instance: UpdateInstance,
    ) -> Result<Instance, Self::Error> {
        todo!()
    }

    async fn get_instance(&self, id: InstanceId) -> Result<Instance, Self::Error> {
        todo!()
    }

    async fn delete_instance(&self, id: InstanceId) -> Result<Instance, Self::Error> {
        todo!()
    }

    async fn list_instances(&self, available_ids: &[InstanceId]) -> Result<Vec<Instance>, Self::Error> {
        todo!()
    }
}
#[allow(unused)]
#[async_trait]
impl ConfigurationRepository for PostgresRepo {
    type Error = AppError;

    async fn create_config(
        &self,
        new_config: NewConfiguration,
    ) -> Result<Configuration, Self::Error> {
        todo!()
    }

    async fn update_config(
        &self,
        id: ConfigurationId,
        update_instance: UpdateConfiguration,
    ) -> Result<Configuration, Self::Error> {
        todo!()
    }

    async fn get_config(&self, id: ConfigurationId) -> Result<Configuration, Self::Error> {
        todo!()
    }

    async fn delete_config(&self, id: ConfigurationId) -> Result<Configuration, Self::Error> {
        todo!()
    }

    async fn list_configs_by_instance(
        &self,
        instance_id: InstanceId,
    ) -> Result<Vec<Configuration>, Self::Error> {
        todo!()
    }

    async fn list_all_configs(&self, available_ids: &[ConfigurationId]) -> Result<Vec<Configuration>, Self::Error> {
        todo!()
    }
}

#[allow(unused)]
#[async_trait]
impl RolesRepository for PostgresRepo {
    type Error = AppError;

    async fn create_role(&self, new_role: NewRole) -> Result<RoleFromRow, Self::Error> {
        todo!()
    }

    async fn update_role(&self, update_role: UpdateRoleDb) -> Result<RoleFromRow, Self::Error> {
        todo!()
    }

    async fn get_role(&self) -> Result<RoleFromRow, Self::Error> {
        todo!()
    }

    async fn delete_role(&self) -> Result<(), Self::Error> {
        todo!()
    }

    async fn list_roles(&self) -> Result<Vec<RoleFromRow>, Self::Error> {
        todo!()
    }
}

#[allow(unused)]
#[async_trait]
impl RightsRepository for PostgresRepo {
    type Error = AppError;

    async fn add_right(&self, right_key: RightKey<'static>, default_value: bool) -> Result<(), Self::Error> {
        todo!()
        // self.ensure_rights_table().await?;
        // let key = String::from(right_key);
        //
        // sqlx::query(
        //     r#"
        //     insert into rights (key, default_value, active)
        //     values ($1, $2, true)
        //     "#,
        // )
        // .bind(&key)
        // .bind(default_value)
        // .execute(&self.pool)
        // .await
        // .map_err(_map_conflict("right"))?;
        //
        // self.publish_rights().await
    }

    async fn add_rights(&self, right_keys: &[RightKey<'static>], default_value: &[bool]) -> Result<(), Self::Error> {
        todo!()
    }

    async fn update_right(
        &self,
        right_key: RightKey<'static>,
        default_value: bool,
    ) -> Result<(), Self::Error> {
        todo!()
        // self.ensure_rights_table().await?;
        // let key = String::from(right_key);
        //
        // let result = sqlx::query(
        //     r#"
        //     update rights
        //     set default_value = $2
        //     where key = $1
        //     "#,
        // )
        // .bind(&key)
        // .bind(default_value)
        // .execute(&self.pool)
        // .await?;
        //
        // if result.rows_affected() == 0 {
        //     return Err(AppError::NotFound(format!("right {key} does not exist")));
        // }
        //
        // self.publish_rights().await
    }

    async fn get_rights(&self) -> Result<Rights, Self::Error> {
        Ok(self.load_rights().await?.into())
    }

    async fn remove_right(&self, right_key: RightKey<'static>) -> Result<(), Self::Error> {
        todo!()
        // self.ensure_rights_table().await?;
        // let key = String::from(right_key);
        //
        // let result = sqlx::query(
        //     r#"
        //     update rights
        //     set active = false
        //     where key = $1
        //     "#,
        // )
        // .bind(&key)
        // .execute(&self.pool)
        // .await?;
        //
        // if result.rows_affected() == 0 {
        //     return Err(AppError::NotFound(format!("right {key} does not exist")));
        // }
        //
        // self.publish_rights().await
    }

    async fn remove_rights(&self, right_keys: &[RightKey<'static>]) -> Result<(), Self::Error> {
        todo!()
    }
}

fn _json<T: Serialize>(value: &T) -> AppResult<sqlx::types::Json<serde_json::Value>> {
    serde_json::to_value(value)
        .map(sqlx::types::Json)
        .map_err(|err| AppError::Internal(err.to_string()))
}

fn _map_conflict(entity: &'static str) -> impl Fn(sqlx::Error) -> AppError {
    move |err| match &err {
        sqlx::Error::Database(db_err) if db_err.is_unique_violation() => {
            AppError::Conflict(format!("{entity} already exists"))
        }
        _ => AppError::Database(err),
    }
}

#[allow(dead_code)]
fn _row_to_timestamp(
    row: &sqlx::postgres::PgRow,
    field: &str,
) -> Result<DateTime<Utc>, sqlx::Error> {
    row.try_get(field)
}
