[package]
name = "rumary-dto"
edition.workspace = true
version.workspace = true

[lib]
name = "rumary_dto"

[dependencies]
chrono.workspace = true
bcrypt.workspace = true
serde.workspace = true
uuid.workspace = true
url.workspace = true
pretty_env_logger.workspace = true
semver = "1.0.28"


[features]
mojang = []
domain_launcher = []
domain_api = []
dto_api = []