[package]
name = "rumary-dto"
edition.workspace = true
version.workspace = true

[lib]
name = "rumary_dto"

[dependencies]
serde.workspace = true
uuid.workspace = true
url = "2.5.8"
chrono = "0.4.45"
semver = "1.0.28"
bcrypt = "0.19.2"


[features]
mojang = []
domain_launcher = []
domain_api = []
dto_api = []